config/routes.rb
Rails.application.routes.draw do
  # 管理者コントローラーのルーディング / アプリケーション詳細設計書参照
  # homes_controllerのルート設定
  # genres_controllerのルーディング
  # items_controllerのルーディング
  # customers_controllerのルーディング
  # orders_controllerのルーディング
  # order_details_controllerのルーディング
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  # 顧客コントローラーのルーディング / アプリケーション詳細設計書参照
  # homes_controllerのルーディング
  # customers_controllerのルーディング
  # items_controllerのルーディング
  # addresses_controllerのルーディング
  # orders_controllerのルーディング
  scope module: 'public' do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'search' => 'items#search'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end

  # 顧客用deviseルーディング設定：URL /customers/sign_in,up ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用deviseルーディング設定：URL /customers/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/models/order.rb
class Order < ApplicationRecord
  # customerモデルとのアソシエーション設定(customer.idの紐付け)
  # order_detailモデルとのアソシエーション設定(order.idの紐付け)
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  # バリデーション設定
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :postage, presence: true
  validates :total_price, presence: true
  validates :payment, presence: true
  validates :order_status, presence: true

  # 支払方法（0=クレジットカード / 1=銀行振込）
  enum payment: {
    credit_card: 0,
    transfer: 1
  }

  # 注文ステータス（0=入金待ち / 1=入金確認 / 2=製作中 / 3=発送準備中 / 4=発送済み）
  enum order_status: {
    wating: 0,
    confirmation: 1,
    making: 2,
    preparation: 3,
    shipped: 4
  }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  # Sign_out中はアクセスできないように設定
  before_action :authenticate_admin!

  # 1ユーザーの注文履歴一覧　※できれば※
  def index
    @customer = current_customer
    @orders = Order.all.page(params[:page]).per(10)
  end

  # 注文履歴詳細画面アクション
  def show
    @order = Order.find(params[:id])
    @order_detail = OrderDetail.find(params[:id])
    @order_details = @order.order_details
  end

  # 注文ステータス編集アクション
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path
  end

  # 注文ステータスのストロングパラメータ
  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<%# 1ユーザーの注文履歴 ※できれば※ %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-auto mb-5 bg-light">
      <h3><%= @customer.last_name + @customer.first_name %>さんの注文履歴</h3>
    </div>

    <div class="col-md-12">
      <table class="table">
        <thead class="table-light">
          <tr>
            <th>購入日時</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id) %></td>
            <td><%= order.order_detail.sum(:amount) %></td>
            <td><%= order.order_status_i18n %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="mx-auto">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<%# 管理者注文履歴詳細画面 %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-auto mb-5 bg-light">
        <h3>注文履歴詳細</h3>
    </div>
    <div class="col-md-8">
    </div>

    <div class="col-md-6 mb-3">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>購入者</th>
            <td>
              <%= link_to admin_customers_path(@order.id) do %>
                <%= @order.customer.last_name %><%= @order.customer.first_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td>
              〒<%= @order.address %><br />
              <%= @order.customer.last_name %><%= @order.customer.first_name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_i18n %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <td>
              <%= form_with model: @order, url: admin_order_path do |f| %>
                <%= f.select :order_status, Order.order_statuses_i18n.invert, {} %>
                <%= f.submit '更新', class: 'btn btn-success' %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
    </div>

    <div class="col-md-8">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
              <%= form_with model: @order_detail, url: admin_order_detail_path, method: :patch do |f| %>
                <td><%= f.select :make_status, OrderDetail.make_statuses_i18n.invert, {} %></td>
                <td><%= f.submit '更新', class: 'btn btn-success' %></td>
              <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-3 mt-4 ml-5">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= (@order.total_price - @order.postage).to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.postage %>円</td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td><%= @order.total_price.to_s(:delimited) %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>