config/routes.rb
Rails.application.routes.draw do
  # 管理者コントローラーのルーディング / アプリケーション詳細設計書参照
  # homes_controllerのルート設定
  # genres_controllerのルーディング
  # items_controllerのルーディング
  # customers_controllerのルーディング
  # orders_controllerのルーディング
  # order_details_controllerのルーディング
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  # 顧客コントローラーのルーディング / アプリケーション詳細設計書参照
  # homes_controllerのルーディング
  # customers_controllerのルーディング
  # items_controllerのルーディング
  # addresses_controllerのルーディング
  # orders_controllerのルーディング
  scope module: 'public' do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'search' => 'items#search'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end

  # 顧客用deviseルーディング設定：URL /customers/sign_in,up ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用deviseルーディング設定：URL /customers/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
  # customerモデルとのアソシエーション設定(customer_idの紐付け)
  belongs_to :customer

  # 登録済み配送先の表示設定
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

  # バリデーション設定
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # customerモデルとのアソシエーション設定(customer_idの紐付け)
  # itemモデルとのアソシエーション設定(item_idの紐付け)
  belongs_to :customer
  belongs_to :item

  # 小計計算
  def subtotal
    item.with_tax_price * amount
  end

  # バリデーション設定
  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # addressモデルとのアソシエーション設定(customer_idの紐付け)
  # cart_itemモデルとのアソシエーション設定(customer_idの紐付け)
  # orderモデルとのアソシエーション設定(customer_idの紐付け)
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # バリデーション設定
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  # itemモデルとのアソシエーション設定(genre_idの紐付け)
  has_many :items, dependent: :destroy

  # バリデーション設定
  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  # genreモデルとのアソシエーション設定(genre_idの紐付け)
  # order_detailモデルとのアソシエーション設定(item.icの紐付け)
  belongs_to :genre
  has_many :order_details, dependent: :destroy

  # バリデーション設定
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true

  # ActiveStoreage：画像使用宣言
  has_one_attached :image

  # 画像が登録されていない場合のエラー回避
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  # 消費税を加えた商品価格
  def with_tax_price
    (price * 1.1).floor
  end

  # 検索機能追加
  def self.search(keyword)
    where(["genre_id like(?)", "%#{keyword}%"])
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # customerモデルとのアソシエーション設定(customer.idの紐付け)
  # order_detailモデルとのアソシエーション設定(order.idの紐付け)
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  # バリデーション設定
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :postage, presence: true
  validates :total_price, presence: true
  validates :payment, presence: true
  validates :order_status, presence: true

  # 支払方法（0=クレジットカード / 1=銀行振込）
  enum payment: {
    credit_card: 0,
    transfer: 1
  }

  # 注文ステータス（0=入金待ち / 1=入金確認 / 2=製作中 / 3=発送準備中 / 4=発送済み）
  enum order_status: {
    wating: 0,
    confirmation: 1,
    making: 2,
    preparation: 3,
    shipped: 4
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  # orderモデルとのアソシエーション設定(order.idの紐付け)
  # itemモデルとのアソシエーション設定(item.idの紐付け)
  belongs_to :order
  belongs_to :item

  # バリデーション設定
  validates :amount, presence: true
  validates :price, presence: true
  validates :make_status, presence: true

  # 製作ステータス（0=着手不可 / 1=製作待ち / 2=製作中 / 3=製作完了）
  enum make_status: {
    not_started: 0,
    wating: 1,
    making: 2,
    completed: 3
  }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  # Sign_out中はアクセスできないように設定
  before_action :authenticate_admin!

  # ジャンル管理画面(一覧・追加)アクション
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  # ジャンル新規登録アクション
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  # ジャンル編集画面アクション
  def edit
    @genre = Genre.find(params[:id])
  end

  # ジャンル編集アクション
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  # 新規登録データのストロングパラメータ
  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  # Sign_out中はアクセスできないように設定
  before_action :authenticate_admin!

  # 注文履歴一覧（トップページ）アクション
  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  # Sign_out中はアクセスできないように設定
  before_action :authenticate_admin!

  # 商品一覧画面アクション
  def index
    @items = Item.page(params[:page])
    @genres= Genre.all
  end

  # 商品新規登録画面アクション
  def new
    @item = Item.new
    @genres = Genre.all
  end

  # 商品新規登録アクション
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  # 商品詳細画面アクション
  def show
    @item = Item.find(params[:id])
  end

  # 商品編集画面アクション
  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  # 商品編集アクション
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  # 新規登録データのストロングパラメータ
  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%# 管理者Sign_in機能のみ実装 %>
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<%# 共通フッター画面 %>
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <p>CopyRight nagano_cake.inc</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<%# 管理者用ヘッダー %>
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag "cake.jpg" %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <%# 管理者Sign_in中 %>
        <% if customer_signed_in? %>
          <li class="nav-item p-2 mr-5 align-items-center">ようこそ、<%= current_customer.last_name %>さん！</li>
          <li class="nav-item p-2"><%= link_to 'マイページ', customers_my_page_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to '商品一覧', items_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to 'カート', cart_items_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark border rounded' %></li>
        <% elsif admin_signed_in? %>
          <li class="nav-item p-2"><%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to '注文履歴一覧', admin_root_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to 'ジャンル一覧' , admin_genres_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border rounded' %></li>
        <%# 管理者Sign_out中 %>
        <% else %>
          <li class="nav-item p-2"><%= link_to 'About', about_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to '商品一覧', items_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-dark border rounded' %></li>
          <li class="nav-item p-2"><%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-dark border rounded' %></li>
        <%# 検索機能　※できれば %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="search-form pb-3">
  <div class="col-10 text-right">
    <%= form_with url: search_path do |f| %>
      <%= f.text_field :keyword, value: @keyword, placeholder: 'search' %>
      <button type=submit>
        <i class="fa fa-search"></i>
      </button>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<%# 全体layout %>
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# application_stylesheet読み込み %>
    <%# Bootstrap読み込み %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%# ヘッダー表示 %>
    <header class="shadow-sm">
      <%# 管理者ヘッダー %>
      <%= render 'layouts/header' %>
    </header>

    <p id="notice">
      <%= notice %>
    </p>
    <%# メイン画面表示 %>
    <main class="mb-5">
      <%= yield %>
    </main>

    <%# フッター表示 %>
    <footer class="bg-light text-dark pt-5 pb-4">
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>